version: '3'
services:
  application:
    container_name: abandonded-pets
    ports:
      - "18082:8080"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://203.241.228.50:13307/pets?useSSL=false&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "mega123"



