spring:
  datasource:
    url: jdbc:mysql://203.241.228.50:13307/pets?useSSL=false&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
    username: root
    password: mega123
    platform: MySQL5Dialect
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true