spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(tAONZgbzXtTltF6GUd2n7uF/f7IJ7fkHy8BO26FZ+lNe/mfCHtGiO4racXPYAYtl)
            redirect_uri: ENC(miaSzuSJU8VjztCLa8vbdtXp3nJhXQZnHLIx4DWXjseVe4U30RXKsp8lwC/qNZO044o1GuBkM7AMtZbGd/Rj1g==)
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

app:
  oauth-redirect-uri: http://localhost:3000/oauth2/redirect