kakao:
  client_id: f572e34312b48d6cebb3d5ce372cf2a7
  redirect_uri: http://localhost:8080/login/oauth2/code/kakao
  client_secret: gPoRjjO0hNzsAYT4Ynd2GCtqsCzBh5ES
  token_uri: https://kauth.kakao.com/oauth/token