spring:
  datasource:
    url: jdbc:mysql:/localhost:13307/pets?useSSL=false&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
    username: root
    password: mega123
    platform: MySQL8Dialect
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true